annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cattle-ui-plugin-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux, windows
  catalog.cattle.io/scope: management
  catalog.cattle.io/ui-component: plugins
  catalog.cattle.io/rancher-version: '>= 2.11.0 < 2.14.0'
  catalog.cattle.io/ui-extensions-version: '>= 3.0.0 < 4.0.0'
  catalog.cattle.io/kube-version: '>= 1.26.0'
  catalog.cattle.io/display-name: Hetzner Cloud Node Driver
apiVersion: v2
appVersion: 1.0.0
description: Hetzner Cloud Node Driver for Rancher
name: hetzner-node-driver
type: application
version: 1.0.0
