nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  endpoint: >-
    https://raw.githubusercontent.com/zsys-studio/rancher-hetzner-cluster-provider/rancher-extension/extensions/hetzner-node-driver/1.0.0
  compressedEndpoint: >-
    https://raw.githubusercontent.com/zsys-studio/rancher-hetzner-cluster-provider/rancher-extension/extensions/hetzner-node-driver/1.0.0.tgz
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/rancher-version: ">= 2.11.0 < 2.14.0"
    catalog.cattle.io/ui-extensions-version: ">= 3.0.0 < 4.0.0"
    catalog.cattle.io/kube-version: ">= 1.26.0"
    catalog.cattle.io/display-name: Hetzner Cloud Node Driver
